version: '3'

services:
  nextjs:
    image: "${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"
    container_name: nextjs
    restart: always
    networks:
      - albertyu-net

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/localhost:/etc/nginx/localhost/:ro
      - ./nginx/dhparam:/etc/letsencrypt/dhparam:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nextjs
    networks:
      - albertyu-net

  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./cloudflare/:/opt/cloudflare/:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --non-interactive --dns-cloudflare --dns-cloudflare-credentials /opt/cloudflare/credentials --keep-until-expiring --agree-tos --email info@albertyu.co -d *.albertyu.co --server https://acme-v02.api.letsencrypt.org/directory

volumes:
  certbot-etc:
  certbot-var:

networks:
  albertyu-net:
    driver: bridge
