import type { NextPage } from 'next'
import Head from 'next/head'
import TestIcon from 'assets/svg/test.svg'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TestIcon />

      <main>
        <h1 sx={{
          fontFamily: 'heading',
        }}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p sx={{
          fontFamily: 'body',
        }}>
          version:
          <code>{process.env.IMAGE_TAG_V}</code>
        </p>
      </main>
    </div>
  )
}

export default Home
