source: /Users/mj12albert/Servers/albertyu.co/source
destination: /Users/mj12albert/Servers/albertyu.co/build
timezone: Asia/Hong_Kong
encoding: utf-8
# host: albertyu.co.dev
# port: 4000
include: [
  '*.scss',
  '*.css.map',
  'js/dist/'
]
exclude: [
  'Gemfile*',
  # 'css/',
  # 'sass/',
  'js/src/',
  '**/*.svg'
  # 'assets/svg/*'
]